<?php

use App\Models\FF_contries;
use Illuminate\Database\Seeder;

class FF_countries_seed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            ['id' => 'af', 'original_name' => 'Afghanistan', 'country_code_alpha2' => 'af', 'translation_key' => 'countries.codes.af', 'country_code_alpha3' => 'afg', 'country_code_m49_numeric' => '4'],
            ['id' => 'ax', 'original_name' => 'Åland Islands', 'country_code_alpha2' => 'ax', 'translation_key' => 'countries.codes.ax', 'country_code_alpha3' => 'ala', 'country_code_m49_numeric' => '248', 'alias' => 'aland islands'],
            ['id' => 'al', 'original_name' => 'Albania', 'country_code_alpha2' => 'al', 'translation_key' => 'countries.codes.al', 'country_code_alpha3' => 'alb', 'country_code_m49_numeric' => '8'],
            ['id' => 'dz', 'original_name' => 'Algeria', 'country_code_alpha2' => 'dz', 'translation_key' => 'countries.codes.dz', 'country_code_alpha3' => 'dza', 'country_code_m49_numeric' => '12'],
            ['id' => 'as', 'original_name' => 'American Samoa', 'country_code_alpha2' => 'as', 'translation_key' => 'countries.codes.as', 'country_code_alpha3' => 'asm', 'country_code_m49_numeric' => '16'],
            ['id' => 'ad', 'original_name' => 'Andorra', 'country_code_alpha2' => 'ad', 'translation_key' => 'countries.codes.ad', 'country_code_alpha3' => 'and', 'country_code_m49_numeric' => '20'],
            ['id' => 'ao', 'original_name' => 'Angola', 'country_code_alpha2' => 'ao', 'translation_key' => 'countries.codes.ao', 'country_code_alpha3' => 'ago', 'country_code_m49_numeric' => '24'],
            ['id' => 'ai', 'original_name' => 'Anguilla', 'country_code_alpha2' => 'ai', 'translation_key' => 'countries.codes.ai', 'country_code_alpha3' => 'aia', 'country_code_m49_numeric' => '660'],
            ['id' => 'aq', 'original_name' => 'Antarctica', 'country_code_alpha2' => 'aq', 'translation_key' => 'countries.codes.aq', 'country_code_alpha3' => 'ata', 'country_code_m49_numeric' => '10'],
            ['id' => 'ag', 'original_name' => 'Antigua and Barbuda', 'country_code_alpha2' => 'ag', 'translation_key' => 'countries.codes.ag', 'country_code_alpha3' => 'atg', 'country_code_m49_numeric' => '28'],
            ['id' => 'ar', 'original_name' => 'Argentina', 'country_code_alpha2' => 'ar', 'translation_key' => 'countries.codes.ar', 'country_code_alpha3' => 'arg', 'country_code_m49_numeric' => '32'],
            ['id' => 'am', 'original_name' => 'Armenia', 'country_code_alpha2' => 'am', 'translation_key' => 'countries.codes.am', 'country_code_alpha3' => 'arm', 'country_code_m49_numeric' => '51'],
            ['id' => 'aw', 'original_name' => 'Aruba', 'country_code_alpha2' => 'aw', 'translation_key' => 'countries.codes.aw', 'country_code_alpha3' => 'abw', 'country_code_m49_numeric' => '533'],
            ['id' => 'au', 'original_name' => 'Australia', 'country_code_alpha2' => 'au', 'translation_key' => 'countries.codes.au', 'country_code_alpha3' => 'aus', 'country_code_m49_numeric' => '36'],
            ['id' => 'at', 'original_name' => 'Austria', 'country_code_alpha2' => 'at', 'translation_key' => 'countries.codes.at', 'country_code_alpha3' => 'aut', 'country_code_m49_numeric' => '40'],
            ['id' => 'az', 'original_name' => 'Azerbaijan', 'country_code_alpha2' => 'az', 'translation_key' => 'countries.codes.az', 'country_code_alpha3' => 'aze', 'country_code_m49_numeric' => '31'],
            ['id' => 'bs', 'original_name' => 'Bahamas', 'country_code_alpha2' => 'bs', 'translation_key' => 'countries.codes.bs', 'country_code_alpha3' => 'bhs', 'country_code_m49_numeric' => '44'],
            ['id' => 'bh', 'original_name' => 'Bahrain', 'country_code_alpha2' => 'bh', 'translation_key' => 'countries.codes.bh', 'country_code_alpha3' => 'bhr', 'country_code_m49_numeric' => '48'],
            ['id' => 'bd', 'original_name' => 'Bangladesh', 'country_code_alpha2' => 'bd', 'translation_key' => 'countries.codes.bd', 'country_code_alpha3' => 'bgd', 'country_code_m49_numeric' => '50'],
            ['id' => 'bb', 'original_name' => 'Barbados', 'country_code_alpha2' => 'bb', 'translation_key' => 'countries.codes.bb', 'country_code_alpha3' => 'brb', 'country_code_m49_numeric' => '52'],
            ['id' => 'by', 'original_name' => 'Belarus', 'country_code_alpha2' => 'by', 'translation_key' => 'countries.codes.by', 'country_code_alpha3' => 'blr', 'country_code_m49_numeric' => '112'],
            ['id' => 'be', 'original_name' => 'Belgium', 'country_code_alpha2' => 'be', 'translation_key' => 'countries.codes.be', 'country_code_alpha3' => 'bel', 'country_code_m49_numeric' => '56'],
            ['id' => 'bz', 'original_name' => 'Belize', 'country_code_alpha2' => 'bz', 'translation_key' => 'countries.codes.bz', 'country_code_alpha3' => 'blz', 'country_code_m49_numeric' => '84'],
            ['id' => 'bj', 'original_name' => 'Benin', 'country_code_alpha2' => 'bj', 'translation_key' => 'countries.codes.bj', 'country_code_alpha3' => 'ben', 'country_code_m49_numeric' => '204'],
            ['id' => 'bm', 'original_name' => 'Bermuda', 'country_code_alpha2' => 'bm', 'translation_key' => 'countries.codes.bm', 'country_code_alpha3' => 'bmu', 'country_code_m49_numeric' => '60'],
            ['id' => 'bt', 'original_name' => 'Bhutan', 'country_code_alpha2' => 'bt', 'translation_key' => 'countries.codes.bt', 'country_code_alpha3' => 'btn', 'country_code_m49_numeric' => '64'],
            ['id' => 'bo', 'original_name' => 'Bolivia (Plurinational State of)', 'country_code_alpha2' => 'bo', 'translation_key' => 'countries.codes.bo', 'country_code_alpha3' => 'bol', 'country_code_m49_numeric' => '68', 'alias' => 'bolivia'],
            ['id' => 'bq', 'original_name' => 'Bonaire, Sint Eustatius and Saba', 'country_code_alpha2' => 'bq', 'translation_key' => 'countries.codes.bq', 'country_code_alpha3' => 'bes', 'country_code_m49_numeric' => '535'],
            ['id' => 'ba', 'original_name' => 'Bosnia and Herzegovina', 'country_code_alpha2' => 'ba', 'translation_key' => 'countries.codes.ba', 'country_code_alpha3' => 'bih', 'country_code_m49_numeric' => '70'],
            ['id' => 'bw', 'original_name' => 'Botswana', 'country_code_alpha2' => 'bw', 'translation_key' => 'countries.codes.bw', 'country_code_alpha3' => 'bwa', 'country_code_m49_numeric' => '72'],
            ['id' => 'bv', 'original_name' => 'Bouvet Island', 'country_code_alpha2' => 'bv', 'translation_key' => 'countries.codes.bv', 'country_code_alpha3' => 'bvt', 'country_code_m49_numeric' => '74'],
            ['id' => 'br', 'original_name' => 'Brazil', 'country_code_alpha2' => 'br', 'translation_key' => 'countries.codes.br', 'country_code_alpha3' => 'bra', 'country_code_m49_numeric' => '76'],
            ['id' => 'io', 'original_name' => 'British Indian Ocean Territory', 'country_code_alpha2' => 'io', 'translation_key' => 'countries.codes.io', 'country_code_alpha3' => 'iot', 'country_code_m49_numeric' => '86'],
            ['id' => 'bn', 'original_name' => 'Brunei Darussalam', 'country_code_alpha2' => 'bn', 'translation_key' => 'countries.codes.bn', 'country_code_alpha3' => 'brn', 'country_code_m49_numeric' => '96'],
            ['id' => 'bg', 'original_name' => 'Bulgaria', 'country_code_alpha2' => 'bg', 'translation_key' => 'countries.codes.bg', 'country_code_alpha3' => 'bgr', 'country_code_m49_numeric' => '100'],
            ['id' => 'bf', 'original_name' => 'Burkina Faso', 'country_code_alpha2' => 'bf', 'translation_key' => 'countries.codes.bf', 'country_code_alpha3' => 'bfa', 'country_code_m49_numeric' => '854'],
            ['id' => 'bi', 'original_name' => 'Burundi', 'country_code_alpha2' => 'bi', 'translation_key' => 'countries.codes.bi', 'country_code_alpha3' => 'bdi', 'country_code_m49_numeric' => '108'],
            ['id' => 'kh', 'original_name' => 'Cambodia', 'country_code_alpha2' => 'kh', 'translation_key' => 'countries.codes.kh', 'country_code_alpha3' => 'khm', 'country_code_m49_numeric' => '116'],
            ['id' => 'cm', 'original_name' => 'Cameroon', 'country_code_alpha2' => 'cm', 'translation_key' => 'countries.codes.cm', 'country_code_alpha3' => 'cmr', 'country_code_m49_numeric' => '120'],
            ['id' => 'ca', 'original_name' => 'Canada', 'country_code_alpha2' => 'ca', 'translation_key' => 'countries.codes.ca', 'country_code_alpha3' => 'can', 'country_code_m49_numeric' => '124'],
            ['id' => 'cv', 'original_name' => 'Cabo Verde', 'country_code_alpha2' => 'cv', 'translation_key' => 'countries.codes.cv', 'country_code_alpha3' => 'cpv', 'country_code_m49_numeric' => '132'],
            ['id' => 'ky', 'original_name' => 'Cayman Islands', 'country_code_alpha2' => 'ky', 'translation_key' => 'countries.codes.ky', 'country_code_alpha3' => 'cym', 'country_code_m49_numeric' => '136'],
            ['id' => 'cf', 'original_name' => 'Central African Republic', 'country_code_alpha2' => 'cf', 'translation_key' => 'countries.codes.cf', 'country_code_alpha3' => 'caf', 'country_code_m49_numeric' => '140'],
            ['id' => 'td', 'original_name' => 'Chad', 'country_code_alpha2' => 'td', 'translation_key' => 'countries.codes.td', 'country_code_alpha3' => 'tcd', 'country_code_m49_numeric' => '148'],
            ['id' => 'cl', 'original_name' => 'Chile', 'country_code_alpha2' => 'cl', 'translation_key' => 'countries.codes.cl', 'country_code_alpha3' => 'chl', 'country_code_m49_numeric' => '152'],
            ['id' => 'cn', 'original_name' => 'China', 'country_code_alpha2' => 'cn', 'translation_key' => 'countries.codes.cn', 'country_code_alpha3' => 'chn', 'country_code_m49_numeric' => '156'],
            ['id' => 'cx', 'original_name' => 'Christmas Island', 'country_code_alpha2' => 'cx', 'translation_key' => 'countries.codes.cx', 'country_code_alpha3' => 'cxr', 'country_code_m49_numeric' => '162'],
            ['id' => 'cc', 'original_name' => 'Cocos (Keeling) Islands', 'country_code_alpha2' => 'cc', 'translation_key' => 'countries.codes.cc', 'country_code_alpha3' => 'cck', 'country_code_m49_numeric' => '166'],
            ['id' => 'co', 'original_name' => 'Colombia', 'country_code_alpha2' => 'co', 'translation_key' => 'countries.codes.co', 'country_code_alpha3' => 'col', 'country_code_m49_numeric' => '170'],
            ['id' => 'km', 'original_name' => 'Comoros', 'country_code_alpha2' => 'km', 'translation_key' => 'countries.codes.km', 'country_code_alpha3' => 'com', 'country_code_m49_numeric' => '174'],
            ['id' => 'cg', 'original_name' => 'Congo', 'country_code_alpha2' => 'cg', 'translation_key' => 'countries.codes.cg', 'country_code_alpha3' => 'cog', 'country_code_m49_numeric' => '178', 'alias' => 'congo'],
            ['id' => 'cd', 'original_name' => 'Congo (Democratic Republic of the)', 'country_code_alpha2' => 'cd', 'translation_key' => 'countries.codes.cd', 'country_code_alpha3' => 'cod', 'country_code_m49_numeric' => '180', 'alias' => 'democratic republic of the congo'],
            ['id' => 'ck', 'original_name' => 'Cook Islands', 'country_code_alpha2' => 'ck', 'translation_key' => 'countries.codes.ck', 'country_code_alpha3' => 'cok', 'country_code_m49_numeric' => '184'],
            ['id' => 'cr', 'original_name' => 'Costa Rica', 'country_code_alpha2' => 'cr', 'translation_key' => 'countries.codes.cr', 'country_code_alpha3' => 'cri', 'country_code_m49_numeric' => '188'],
            ['id' => 'ci', 'original_name' => 'Côte d\'Ivoire', 'country_code_alpha2' => 'ci', 'translation_key' => 'countries.codes.ci', 'country_code_alpha3' => 'civ', 'country_code_m49_numeric' => '384', 'alias' => 'ivory coast'],
            ['id' => 'hr', 'original_name' => 'Croatia', 'country_code_alpha2' => 'hr', 'translation_key' => 'countries.codes.hr', 'country_code_alpha3' => 'hrv', 'country_code_m49_numeric' => '191'],
            ['id' => 'cu', 'original_name' => 'Cuba', 'country_code_alpha2' => 'cu', 'translation_key' => 'countries.codes.cu', 'country_code_alpha3' => 'cub', 'country_code_m49_numeric' => '192'],
            ['id' => 'cw', 'original_name' => 'Curaçao', 'country_code_alpha2' => 'cw', 'translation_key' => 'countries.codes.cw', 'country_code_alpha3' => 'cuw', 'country_code_m49_numeric' => '531', 'alias' => 'curacao'],
            ['id' => 'cy', 'original_name' => 'Cyprus', 'country_code_alpha2' => 'cy', 'translation_key' => 'countries.codes.cy', 'country_code_alpha3' => 'cyp', 'country_code_m49_numeric' => '196'],
            ['id' => 'cz', 'original_name' => 'Czech Republic', 'country_code_alpha2' => 'cz', 'translation_key' => 'countries.codes.cz', 'country_code_alpha3' => 'cze', 'country_code_m49_numeric' => '203', 'alias' => 'czechoslovakia'],
            ['id' => 'dk', 'original_name' => 'Denmark', 'country_code_alpha2' => 'dk', 'translation_key' => 'countries.codes.dk', 'country_code_alpha3' => 'dnk', 'country_code_m49_numeric' => '208'],
            ['id' => 'dj', 'original_name' => 'Djibouti', 'country_code_alpha2' => 'dj', 'translation_key' => 'countries.codes.dj', 'country_code_alpha3' => 'dji', 'country_code_m49_numeric' => '262'],
            ['id' => 'dm', 'original_name' => 'Dominica', 'country_code_alpha2' => 'dm', 'translation_key' => 'countries.codes.dm', 'country_code_alpha3' => 'dma', 'country_code_m49_numeric' => '212'],
            ['id' => 'do', 'original_name' => 'Dominican Republic', 'country_code_alpha2' => 'do', 'translation_key' => 'countries.codes.do', 'country_code_alpha3' => 'dom', 'country_code_m49_numeric' => '214'],
            ['id' => 'ec', 'original_name' => 'Ecuador', 'country_code_alpha2' => 'ec', 'translation_key' => 'countries.codes.ec', 'country_code_alpha3' => 'ecu', 'country_code_m49_numeric' => '218'],
            ['id' => 'eg', 'original_name' => 'Egypt', 'country_code_alpha2' => 'eg', 'translation_key' => 'countries.codes.eg', 'country_code_alpha3' => 'egy', 'country_code_m49_numeric' => '818'],
            ['id' => 'sv', 'original_name' => 'El Salvador', 'country_code_alpha2' => 'sv', 'translation_key' => 'countries.codes.sv', 'country_code_alpha3' => 'slv', 'country_code_m49_numeric' => '222'],
            ['id' => 'gq', 'original_name' => 'Equatorial Guinea', 'country_code_alpha2' => 'gq', 'translation_key' => 'countries.codes.gq', 'country_code_alpha3' => 'gnq', 'country_code_m49_numeric' => '226'],
            ['id' => 'er', 'original_name' => 'Eritrea', 'country_code_alpha2' => 'er', 'translation_key' => 'countries.codes.er', 'country_code_alpha3' => 'eri', 'country_code_m49_numeric' => '232'],
            ['id' => 'ee', 'original_name' => 'Estonia', 'country_code_alpha2' => 'ee', 'translation_key' => 'countries.codes.ee', 'country_code_alpha3' => 'est', 'country_code_m49_numeric' => '233'],
            ['id' => 'et', 'original_name' => 'Ethiopia', 'country_code_alpha2' => 'et', 'translation_key' => 'countries.codes.et', 'country_code_alpha3' => 'eth', 'country_code_m49_numeric' => '231'],
            ['id' => 'fk', 'original_name' => 'Falkland Islands (Malvinas)', 'country_code_alpha2' => 'fk', 'translation_key' => 'countries.codes.fk', 'country_code_alpha3' => 'flk', 'country_code_m49_numeric' => '238', 'alias' => 'falkland islands'],
            ['id' => 'fo', 'original_name' => 'Faroe Islands', 'country_code_alpha2' => 'fo', 'translation_key' => 'countries.codes.fo', 'country_code_alpha3' => 'fro', 'country_code_m49_numeric' => '234'],
            ['id' => 'fj', 'original_name' => 'Fiji', 'country_code_alpha2' => 'fj', 'translation_key' => 'countries.codes.fj', 'country_code_alpha3' => 'fji', 'country_code_m49_numeric' => '242'],
            ['id' => 'fi', 'original_name' => 'Finland', 'country_code_alpha2' => 'fi', 'translation_key' => 'countries.codes.fi', 'country_code_alpha3' => 'fin', 'country_code_m49_numeric' => '246'],
            ['id' => 'fr', 'original_name' => 'France', 'country_code_alpha2' => 'fr', 'translation_key' => 'countries.codes.fr', 'country_code_alpha3' => 'fra', 'country_code_m49_numeric' => '250'],
            ['id' => 'gf', 'original_name' => 'French Guiana', 'country_code_alpha2' => 'gf', 'translation_key' => 'countries.codes.gf', 'country_code_alpha3' => 'guf', 'country_code_m49_numeric' => '254'],
            ['id' => 'pf', 'original_name' => 'French Polynesia', 'country_code_alpha2' => 'pf', 'translation_key' => 'countries.codes.pf', 'country_code_alpha3' => 'pyf', 'country_code_m49_numeric' => '258'],
            ['id' => 'tf', 'original_name' => 'French Southern Territories', 'country_code_alpha2' => 'tf', 'translation_key' => 'countries.codes.tf', 'country_code_alpha3' => 'atf', 'country_code_m49_numeric' => '260'],
            ['id' => 'ga', 'original_name' => 'Gabon', 'country_code_alpha2' => 'ga', 'translation_key' => 'countries.codes.ga', 'country_code_alpha3' => 'gab', 'country_code_m49_numeric' => '266'],
            ['id' => 'gm', 'original_name' => 'Gambia', 'country_code_alpha2' => 'gm', 'translation_key' => 'countries.codes.gm', 'country_code_alpha3' => 'gmb', 'country_code_m49_numeric' => '270'],
            ['id' => 'ge', 'original_name' => 'Georgia', 'country_code_alpha2' => 'ge', 'translation_key' => 'countries.codes.ge', 'country_code_alpha3' => 'geo', 'country_code_m49_numeric' => '268'],
            ['id' => 'de', 'original_name' => 'Germany', 'country_code_alpha2' => 'de', 'translation_key' => 'countries.codes.de', 'country_code_alpha3' => 'deu', 'country_code_m49_numeric' => '276', 'alias' => 'west germany;east germany'],
            ['id' => 'gh', 'original_name' => 'Ghana', 'country_code_alpha2' => 'gh', 'translation_key' => 'countries.codes.gh', 'country_code_alpha3' => 'gha', 'country_code_m49_numeric' => '288'],
            ['id' => 'gi', 'original_name' => 'Gibraltar', 'country_code_alpha2' => 'gi', 'translation_key' => 'countries.codes.gi', 'country_code_alpha3' => 'gib', 'country_code_m49_numeric' => '292'],
            ['id' => 'gr', 'original_name' => 'Greece', 'country_code_alpha2' => 'gr', 'translation_key' => 'countries.codes.gr', 'country_code_alpha3' => 'grc', 'country_code_m49_numeric' => '300'],
            ['id' => 'gl', 'original_name' => 'Greenland', 'country_code_alpha2' => 'gl', 'translation_key' => 'countries.codes.gl', 'country_code_alpha3' => 'grl', 'country_code_m49_numeric' => '304'],
            ['id' => 'gd', 'original_name' => 'Grenada', 'country_code_alpha2' => 'gd', 'translation_key' => 'countries.codes.gd', 'country_code_alpha3' => 'grd', 'country_code_m49_numeric' => '308'],
            ['id' => 'gp', 'original_name' => 'Guadeloupe', 'country_code_alpha2' => 'gp', 'translation_key' => 'countries.codes.gp', 'country_code_alpha3' => 'glp', 'country_code_m49_numeric' => '312'],
            ['id' => 'gu', 'original_name' => 'Guam', 'country_code_alpha2' => 'gu', 'translation_key' => 'countries.codes.gu', 'country_code_alpha3' => 'gum', 'country_code_m49_numeric' => '316'],
            ['id' => 'gt', 'original_name' => 'Guatemala', 'country_code_alpha2' => 'gt', 'translation_key' => 'countries.codes.gt', 'country_code_alpha3' => 'gtm', 'country_code_m49_numeric' => '320'],
            ['id' => 'gg', 'original_name' => 'Guernsey', 'country_code_alpha2' => 'gg', 'translation_key' => 'countries.codes.gg', 'country_code_alpha3' => 'ggy', 'country_code_m49_numeric' => '831'],
            ['id' => 'gn', 'original_name' => 'Guinea', 'country_code_alpha2' => 'gn', 'translation_key' => 'countries.codes.gn', 'country_code_alpha3' => 'gin', 'country_code_m49_numeric' => '324'],
            ['id' => 'gw', 'original_name' => 'Guinea-Bissau', 'country_code_alpha2' => 'gw', 'translation_key' => 'countries.codes.gw', 'country_code_alpha3' => 'gnb', 'country_code_m49_numeric' => '624'],
            ['id' => 'gy', 'original_name' => 'Guyana', 'country_code_alpha2' => 'gy', 'translation_key' => 'countries.codes.gy', 'country_code_alpha3' => 'guy', 'country_code_m49_numeric' => '328'],
            ['id' => 'ht', 'original_name' => 'Haiti', 'country_code_alpha2' => 'ht', 'translation_key' => 'countries.codes.ht', 'country_code_alpha3' => 'hti', 'country_code_m49_numeric' => '332'],
            ['id' => 'hm', 'original_name' => 'Heard Island and McDonald Islands', 'country_code_alpha2' => 'hm', 'translation_key' => 'countries.codes.hm', 'country_code_alpha3' => 'hmd', 'country_code_m49_numeric' => '334'],
            ['id' => 'va', 'original_name' => 'Holy See', 'country_code_alpha2' => 'va', 'translation_key' => 'countries.codes.va', 'country_code_alpha3' => 'vat', 'country_code_m49_numeric' => '336'],
            ['id' => 'hn', 'original_name' => 'Honduras', 'country_code_alpha2' => 'hn', 'translation_key' => 'countries.codes.hn', 'country_code_alpha3' => 'hnd', 'country_code_m49_numeric' => '340'],
            ['id' => 'hk', 'original_name' => 'Hong Kong', 'country_code_alpha2' => 'hk', 'translation_key' => 'countries.codes.hk', 'country_code_alpha3' => 'hkg', 'country_code_m49_numeric' => '344'],
            ['id' => 'hu', 'original_name' => 'Hungary', 'country_code_alpha2' => 'hu', 'translation_key' => 'countries.codes.hu', 'country_code_alpha3' => 'hun', 'country_code_m49_numeric' => '348'],
            ['id' => 'is', 'original_name' => 'Iceland', 'country_code_alpha2' => 'is', 'translation_key' => 'countries.codes.is', 'country_code_alpha3' => 'isl', 'country_code_m49_numeric' => '352'],
            ['id' => 'in', 'original_name' => 'India', 'country_code_alpha2' => 'in', 'translation_key' => 'countries.codes.in', 'country_code_alpha3' => 'ind', 'country_code_m49_numeric' => '356'],
            ['id' => 'id', 'original_name' => 'Indonesia', 'country_code_alpha2' => 'id', 'translation_key' => 'countries.codes.id', 'country_code_alpha3' => 'idn', 'country_code_m49_numeric' => '360'],
            ['id' => 'ir', 'original_name' => 'Iran (Islamic Republic of)', 'country_code_alpha2' => 'ir', 'translation_key' => 'countries.codes.ir', 'country_code_alpha3' => 'irn', 'country_code_m49_numeric' => '364', 'alias' => 'iran'],
            ['id' => 'iq', 'original_name' => 'Iraq', 'country_code_alpha2' => 'iq', 'translation_key' => 'countries.codes.iq', 'country_code_alpha3' => 'irq', 'country_code_m49_numeric' => '368'],
            ['id' => 'ie', 'original_name' => 'Ireland', 'country_code_alpha2' => 'ie', 'translation_key' => 'countries.codes.ie', 'country_code_alpha3' => 'irl', 'country_code_m49_numeric' => '372'],
            ['id' => 'im', 'original_name' => 'Isle of Man', 'country_code_alpha2' => 'im', 'translation_key' => 'countries.codes.im', 'country_code_alpha3' => 'imn', 'country_code_m49_numeric' => '833'],
            ['id' => 'il', 'original_name' => 'Israel', 'country_code_alpha2' => 'il', 'translation_key' => 'countries.codes.il', 'country_code_alpha3' => 'isr', 'country_code_m49_numeric' => '376'],
            ['id' => 'it', 'original_name' => 'Italy', 'country_code_alpha2' => 'it', 'translation_key' => 'countries.codes.it', 'country_code_alpha3' => 'ita', 'country_code_m49_numeric' => '380'],
            ['id' => 'jm', 'original_name' => 'Jamaica', 'country_code_alpha2' => 'jm', 'translation_key' => 'countries.codes.jm', 'country_code_alpha3' => 'jam', 'country_code_m49_numeric' => '388'],
            ['id' => 'jp', 'original_name' => 'Japan', 'country_code_alpha2' => 'jp', 'translation_key' => 'countries.codes.jp', 'country_code_alpha3' => 'jpn', 'country_code_m49_numeric' => '392'],
            ['id' => 'je', 'original_name' => 'Jersey', 'country_code_alpha2' => 'je', 'translation_key' => 'countries.codes.je', 'country_code_alpha3' => 'jey', 'country_code_m49_numeric' => '832'],
            ['id' => 'jo', 'original_name' => 'Jordan', 'country_code_alpha2' => 'jo', 'translation_key' => 'countries.codes.jo', 'country_code_alpha3' => 'jor', 'country_code_m49_numeric' => '400'],
            ['id' => 'kz', 'original_name' => 'Kazakhstan', 'country_code_alpha2' => 'kz', 'translation_key' => 'countries.codes.kz', 'country_code_alpha3' => 'kaz', 'country_code_m49_numeric' => '398'],
            ['id' => 'ke', 'original_name' => 'Kenya', 'country_code_alpha2' => 'ke', 'translation_key' => 'countries.codes.ke', 'country_code_alpha3' => 'ken', 'country_code_m49_numeric' => '404'],
            ['id' => 'ki', 'original_name' => 'Kiribati', 'country_code_alpha2' => 'ki', 'translation_key' => 'countries.codes.ki', 'country_code_alpha3' => 'kir', 'country_code_m49_numeric' => '296'],
            ['id' => 'kp', 'original_name' => 'Korea (Democratic People\'s Republic of)', 'country_code_alpha2' => 'kp', 'translation_key' => 'countries.codes.kp', 'country_code_alpha3' => 'prk', 'country_code_m49_numeric' => '408', 'alias' => 'north korea'],
            ['id' => 'kr', 'original_name' => 'Korea (Republic of)', 'country_code_alpha2' => 'kr', 'translation_key' => 'countries.codes.kr', 'country_code_alpha3' => 'kor', 'country_code_m49_numeric' => '410', 'alias' => 'south korea'],
            ['id' => 'kw', 'original_name' => 'Kuwait', 'country_code_alpha2' => 'kw', 'translation_key' => 'countries.codes.kw', 'country_code_alpha3' => 'kwt', 'country_code_m49_numeric' => '414'],
            ['id' => 'kg', 'original_name' => 'Kyrgyzstan', 'country_code_alpha2' => 'kg', 'translation_key' => 'countries.codes.kg', 'country_code_alpha3' => 'kgz', 'country_code_m49_numeric' => '417'],
            ['id' => 'la', 'original_name' => 'Lao People\'s Democratic Republic', 'country_code_alpha2' => 'la', 'translation_key' => 'countries.codes.la', 'country_code_alpha3' => 'lao', 'country_code_m49_numeric' => '418', 'alias' => 'laos'],
            ['id' => 'lv', 'original_name' => 'Latvia', 'country_code_alpha2' => 'lv', 'translation_key' => 'countries.codes.lv', 'country_code_alpha3' => 'lva', 'country_code_m49_numeric' => '428'],
            ['id' => 'lb', 'original_name' => 'Lebanon', 'country_code_alpha2' => 'lb', 'translation_key' => 'countries.codes.lb', 'country_code_alpha3' => 'lbn', 'country_code_m49_numeric' => '422'],
            ['id' => 'ls', 'original_name' => 'Lesotho', 'country_code_alpha2' => 'ls', 'translation_key' => 'countries.codes.ls', 'country_code_alpha3' => 'lso', 'country_code_m49_numeric' => '426'],
            ['id' => 'lr', 'original_name' => 'Liberia', 'country_code_alpha2' => 'lr', 'translation_key' => 'countries.codes.lr', 'country_code_alpha3' => 'lbr', 'country_code_m49_numeric' => '430'],
            ['id' => 'ly', 'original_name' => 'Libya', 'country_code_alpha2' => 'ly', 'translation_key' => 'countries.codes.ly', 'country_code_alpha3' => 'lby', 'country_code_m49_numeric' => '434'],
            ['id' => 'li', 'original_name' => 'Liechtenstein', 'country_code_alpha2' => 'li', 'translation_key' => 'countries.codes.li', 'country_code_alpha3' => 'lie', 'country_code_m49_numeric' => '438'],
            ['id' => 'lt', 'original_name' => 'Lithuania', 'country_code_alpha2' => 'lt', 'translation_key' => 'countries.codes.lt', 'country_code_alpha3' => 'ltu', 'country_code_m49_numeric' => '440'],
            ['id' => 'lu', 'original_name' => 'Luxembourg', 'country_code_alpha2' => 'lu', 'translation_key' => 'countries.codes.lu', 'country_code_alpha3' => 'lux', 'country_code_m49_numeric' => '442'],
            ['id' => 'mo', 'original_name' => 'Macao', 'country_code_alpha2' => 'mo', 'translation_key' => 'countries.codes.mo', 'country_code_alpha3' => 'mac', 'country_code_m49_numeric' => '446'],
            ['id' => 'mk', 'original_name' => 'Macedonia (the former Yugoslav Republic of)', 'country_code_alpha2' => 'mk', 'translation_key' => 'countries.codes.mk', 'country_code_alpha3' => 'mkd', 'country_code_m49_numeric' => '807', 'alias' => 'republic of macedonia'],
            ['id' => 'mg', 'original_name' => 'Madagascar', 'country_code_alpha2' => 'mg', 'translation_key' => 'countries.codes.mg', 'country_code_alpha3' => 'mdg', 'country_code_m49_numeric' => '450'],
            ['id' => 'mw', 'original_name' => 'Malawi', 'country_code_alpha2' => 'mw', 'translation_key' => 'countries.codes.mw', 'country_code_alpha3' => 'mwi', 'country_code_m49_numeric' => '454'],
            ['id' => 'my', 'original_name' => 'Malaysia', 'country_code_alpha2' => 'my', 'translation_key' => 'countries.codes.my', 'country_code_alpha3' => 'mys', 'country_code_m49_numeric' => '458'],
            ['id' => 'mv', 'original_name' => 'Maldives', 'country_code_alpha2' => 'mv', 'translation_key' => 'countries.codes.mv', 'country_code_alpha3' => 'mdv', 'country_code_m49_numeric' => '462'],
            ['id' => 'ml', 'original_name' => 'Mali', 'country_code_alpha2' => 'ml', 'translation_key' => 'countries.codes.ml', 'country_code_alpha3' => 'mli', 'country_code_m49_numeric' => '466'],
            ['id' => 'mt', 'original_name' => 'Malta', 'country_code_alpha2' => 'mt', 'translation_key' => 'countries.codes.mt', 'country_code_alpha3' => 'mlt', 'country_code_m49_numeric' => '470'],
            ['id' => 'mh', 'original_name' => 'Marshall Islands', 'country_code_alpha2' => 'mh', 'translation_key' => 'countries.codes.mh', 'country_code_alpha3' => 'mhl', 'country_code_m49_numeric' => '584'],
            ['id' => 'mq', 'original_name' => 'Martinique', 'country_code_alpha2' => 'mq', 'translation_key' => 'countries.codes.mq', 'country_code_alpha3' => 'mtq', 'country_code_m49_numeric' => '474'],
            ['id' => 'mr', 'original_name' => 'Mauritania', 'country_code_alpha2' => 'mr', 'translation_key' => 'countries.codes.mr', 'country_code_alpha3' => 'mrt', 'country_code_m49_numeric' => '478'],
            ['id' => 'mu', 'original_name' => 'Mauritius', 'country_code_alpha2' => 'mu', 'translation_key' => 'countries.codes.mu', 'country_code_alpha3' => 'mus', 'country_code_m49_numeric' => '480'],
            ['id' => 'yt', 'original_name' => 'Mayotte', 'country_code_alpha2' => 'yt', 'translation_key' => 'countries.codes.yt', 'country_code_alpha3' => 'myt', 'country_code_m49_numeric' => '175'],
            ['id' => 'mx', 'original_name' => 'Mexico', 'country_code_alpha2' => 'mx', 'translation_key' => 'countries.codes.mx', 'country_code_alpha3' => 'mex', 'country_code_m49_numeric' => '484'],
            ['id' => 'fm', 'original_name' => 'Micronesia (Federated States of)', 'country_code_alpha2' => 'fm', 'translation_key' => 'countries.codes.fm', 'country_code_alpha3' => 'fsm', 'country_code_m49_numeric' => '583', 'alias' => 'micronesia;federated states of micronesia'],
            ['id' => 'md', 'original_name' => 'Moldova (Republic of)', 'country_code_alpha2' => 'md', 'translation_key' => 'countries.codes.md', 'country_code_alpha3' => 'mda', 'country_code_m49_numeric' => '498', 'alias' => 'moldova'],
            ['id' => 'mc', 'original_name' => 'Monaco', 'country_code_alpha2' => 'mc', 'translation_key' => 'countries.codes.mc', 'country_code_alpha3' => 'mco', 'country_code_m49_numeric' => '492'],
            ['id' => 'mn', 'original_name' => 'Mongolia', 'country_code_alpha2' => 'mn', 'translation_key' => 'countries.codes.mn', 'country_code_alpha3' => 'mng', 'country_code_m49_numeric' => '496'],
            ['id' => 'me', 'original_name' => 'Montenegro', 'country_code_alpha2' => 'me', 'translation_key' => 'countries.codes.me', 'country_code_alpha3' => 'mne', 'country_code_m49_numeric' => '499'],
            ['id' => 'ms', 'original_name' => 'Montserrat', 'country_code_alpha2' => 'ms', 'translation_key' => 'countries.codes.ms', 'country_code_alpha3' => 'msr', 'country_code_m49_numeric' => '500'],
            ['id' => 'ma', 'original_name' => 'Morocco', 'country_code_alpha2' => 'ma', 'translation_key' => 'countries.codes.ma', 'country_code_alpha3' => 'mar', 'country_code_m49_numeric' => '504'],
            ['id' => 'mz', 'original_name' => 'Mozambique', 'country_code_alpha2' => 'mz', 'translation_key' => 'countries.codes.mz', 'country_code_alpha3' => 'moz', 'country_code_m49_numeric' => '508'],
            ['id' => 'mm', 'original_name' => 'Myanmar', 'country_code_alpha2' => 'mm', 'translation_key' => 'countries.codes.mm', 'country_code_alpha3' => 'mmr', 'country_code_m49_numeric' => '104'],
            ['id' => 'na', 'original_name' => 'Namibia', 'country_code_alpha2' => 'na', 'translation_key' => 'countries.codes.na', 'country_code_alpha3' => 'nam', 'country_code_m49_numeric' => '516'],
            ['id' => 'nr', 'original_name' => 'Nauru', 'country_code_alpha2' => 'nr', 'translation_key' => 'countries.codes.nr', 'country_code_alpha3' => 'nru', 'country_code_m49_numeric' => '520'],
            ['id' => 'np', 'original_name' => 'Nepal', 'country_code_alpha2' => 'np', 'translation_key' => 'countries.codes.np', 'country_code_alpha3' => 'npl', 'country_code_m49_numeric' => '524'],
            ['id' => 'nl', 'original_name' => 'Netherlands', 'country_code_alpha2' => 'nl', 'translation_key' => 'countries.codes.nl', 'country_code_alpha3' => 'nld', 'country_code_m49_numeric' => '528'],
            ['id' => 'nc', 'original_name' => 'New Caledonia', 'country_code_alpha2' => 'nc', 'translation_key' => 'countries.codes.nc', 'country_code_alpha3' => 'ncl', 'country_code_m49_numeric' => '540'],
            ['id' => 'nz', 'original_name' => 'New Zealand', 'country_code_alpha2' => 'nz', 'translation_key' => 'countries.codes.nz', 'country_code_alpha3' => 'nzl', 'country_code_m49_numeric' => '554'],
            ['id' => 'ni', 'original_name' => 'Nicaragua', 'country_code_alpha2' => 'ni', 'translation_key' => 'countries.codes.ni', 'country_code_alpha3' => 'nic', 'country_code_m49_numeric' => '558'],
            ['id' => 'ne', 'original_name' => 'Niger', 'country_code_alpha2' => 'ne', 'translation_key' => 'countries.codes.ne', 'country_code_alpha3' => 'ner', 'country_code_m49_numeric' => '562'],
            ['id' => 'ng', 'original_name' => 'Nigeria', 'country_code_alpha2' => 'ng', 'translation_key' => 'countries.codes.ng', 'country_code_alpha3' => 'nga', 'country_code_m49_numeric' => '566'],
            ['id' => 'nu', 'original_name' => 'Niue', 'country_code_alpha2' => 'nu', 'translation_key' => 'countries.codes.nu', 'country_code_alpha3' => 'niu', 'country_code_m49_numeric' => '570'],
            ['id' => 'nf', 'original_name' => 'Norfolk Island', 'country_code_alpha2' => 'nf', 'translation_key' => 'countries.codes.nf', 'country_code_alpha3' => 'nfk', 'country_code_m49_numeric' => '574'],
            ['id' => 'mp', 'original_name' => 'Northern Mariana Islands', 'country_code_alpha2' => 'mp', 'translation_key' => 'countries.codes.mp', 'country_code_alpha3' => 'mnp', 'country_code_m49_numeric' => '580'],
            ['id' => 'no', 'original_name' => 'Norway', 'country_code_alpha2' => 'no', 'translation_key' => 'countries.codes.no', 'country_code_alpha3' => 'nor', 'country_code_m49_numeric' => '578'],
            ['id' => 'om', 'original_name' => 'Oman', 'country_code_alpha2' => 'om', 'translation_key' => 'countries.codes.om', 'country_code_alpha3' => 'omn', 'country_code_m49_numeric' => '512'],
            ['id' => 'pk', 'original_name' => 'Pakistan', 'country_code_alpha2' => 'pk', 'translation_key' => 'countries.codes.pk', 'country_code_alpha3' => 'pak', 'country_code_m49_numeric' => '586'],
            ['id' => 'pw', 'original_name' => 'Palau', 'country_code_alpha2' => 'pw', 'translation_key' => 'countries.codes.pw', 'country_code_alpha3' => 'plw', 'country_code_m49_numeric' => '585'],
            ['id' => 'ps', 'original_name' => 'Palestine, State of', 'country_code_alpha2' => 'ps', 'translation_key' => 'countries.codes.ps', 'country_code_alpha3' => 'pse', 'country_code_m49_numeric' => '275'],
            ['id' => 'pa', 'original_name' => 'Panama', 'country_code_alpha2' => 'pa', 'translation_key' => 'countries.codes.pa', 'country_code_alpha3' => 'pan', 'country_code_m49_numeric' => '591'],
            ['id' => 'pg', 'original_name' => 'Papua New Guinea', 'country_code_alpha2' => 'pg', 'translation_key' => 'countries.codes.pg', 'country_code_alpha3' => 'png', 'country_code_m49_numeric' => '598'],
            ['id' => 'py', 'original_name' => 'Paraguay', 'country_code_alpha2' => 'py', 'translation_key' => 'countries.codes.py', 'country_code_alpha3' => 'pry', 'country_code_m49_numeric' => '600'],
            ['id' => 'pe', 'original_name' => 'Peru', 'country_code_alpha2' => 'pe', 'translation_key' => 'countries.codes.pe', 'country_code_alpha3' => 'per', 'country_code_m49_numeric' => '604'],
            ['id' => 'ph', 'original_name' => 'Philippines', 'country_code_alpha2' => 'ph', 'translation_key' => 'countries.codes.ph', 'country_code_alpha3' => 'phl', 'country_code_m49_numeric' => '608'],
            ['id' => 'pn', 'original_name' => 'Pitcairn', 'country_code_alpha2' => 'pn', 'translation_key' => 'countries.codes.pn', 'country_code_alpha3' => 'pcn', 'country_code_m49_numeric' => '612'],
            ['id' => 'pl', 'original_name' => 'Poland', 'country_code_alpha2' => 'pl', 'translation_key' => 'countries.codes.pl', 'country_code_alpha3' => 'pol', 'country_code_m49_numeric' => '616'],
            ['id' => 'pt', 'original_name' => 'Portugal', 'country_code_alpha2' => 'pt', 'translation_key' => 'countries.codes.pt', 'country_code_alpha3' => 'prt', 'country_code_m49_numeric' => '620'],
            ['id' => 'pr', 'original_name' => 'Puerto Rico', 'country_code_alpha2' => 'pr', 'translation_key' => 'countries.codes.pr', 'country_code_alpha3' => 'pri', 'country_code_m49_numeric' => '630'],
            ['id' => 'qa', 'original_name' => 'Qatar', 'country_code_alpha2' => 'qa', 'translation_key' => 'countries.codes.qa', 'country_code_alpha3' => 'qat', 'country_code_m49_numeric' => '634'],
            ['id' => 're', 'original_name' => 'Réunion', 'country_code_alpha2' => 're', 'translation_key' => 'countries.codes.re', 'country_code_alpha3' => 'reu', 'country_code_m49_numeric' => '638', 'alias' => 'reunion'],
            ['id' => 'ro', 'original_name' => 'Romania', 'country_code_alpha2' => 'ro', 'translation_key' => 'countries.codes.ro', 'country_code_alpha3' => 'rou', 'country_code_m49_numeric' => '642'],
            ['id' => 'ru', 'original_name' => 'Russian Federation', 'country_code_alpha2' => 'ru', 'translation_key' => 'countries.codes.ru', 'country_code_alpha3' => 'rus', 'country_code_m49_numeric' => '643', 'alias' => 'russia;soviet union'],
            ['id' => 'rw', 'original_name' => 'Rwanda', 'country_code_alpha2' => 'rw', 'translation_key' => 'countries.codes.rw', 'country_code_alpha3' => 'rwa', 'country_code_m49_numeric' => '646'],
            ['id' => 'bl', 'original_name' => 'Saint Barthélemy', 'country_code_alpha2' => 'bl', 'translation_key' => 'countries.codes.bl', 'country_code_alpha3' => 'blm', 'country_code_m49_numeric' => '652'],
            ['id' => 'sh', 'original_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_code_alpha2' => 'sh', 'translation_key' => 'countries.codes.sh', 'country_code_alpha3' => 'shn', 'country_code_m49_numeric' => '654', 'alias' => 'saint helena'],
            ['id' => 'kn', 'original_name' => 'Saint Kitts and Nevis', 'country_code_alpha2' => 'kn', 'translation_key' => 'countries.codes.kn', 'country_code_alpha3' => 'kna', 'country_code_m49_numeric' => '659'],
            ['id' => 'lc', 'original_name' => 'Saint Lucia', 'country_code_alpha2' => 'lc', 'translation_key' => 'countries.codes.lc', 'country_code_alpha3' => 'lca', 'country_code_m49_numeric' => '662'],
            ['id' => 'mf', 'original_name' => 'Saint Martin (French part)', 'country_code_alpha2' => 'mf', 'translation_key' => 'countries.codes.mf', 'country_code_alpha3' => 'maf', 'country_code_m49_numeric' => '663', 'alias' => 'saint martin'],
            ['id' => 'pm', 'original_name' => 'Saint Pierre and Miquelon', 'country_code_alpha2' => 'pm', 'translation_key' => 'countries.codes.pm', 'country_code_alpha3' => 'spm', 'country_code_m49_numeric' => '666'],
            ['id' => 'vc', 'original_name' => 'Saint Vincent and the Grenadines', 'country_code_alpha2' => 'vc', 'translation_key' => 'countries.codes.vc', 'country_code_alpha3' => 'vct', 'country_code_m49_numeric' => '670'],
            ['id' => 'ws', 'original_name' => 'Samoa', 'country_code_alpha2' => 'ws', 'translation_key' => 'countries.codes.ws', 'country_code_alpha3' => 'wsm', 'country_code_m49_numeric' => '882'],
            ['id' => 'sm', 'original_name' => 'San Marino', 'country_code_alpha2' => 'sm', 'translation_key' => 'countries.codes.sm', 'country_code_alpha3' => 'smr', 'country_code_m49_numeric' => '674'],
            ['id' => 'st', 'original_name' => 'Sao Tome and Principe', 'country_code_alpha2' => 'st', 'translation_key' => 'countries.codes.st', 'country_code_alpha3' => 'stp', 'country_code_m49_numeric' => '678'],
            ['id' => 'sa', 'original_name' => 'Saudi Arabia', 'country_code_alpha2' => 'sa', 'translation_key' => 'countries.codes.sa', 'country_code_alpha3' => 'sau', 'country_code_m49_numeric' => '682'],
            ['id' => 'sn', 'original_name' => 'Senegal', 'country_code_alpha2' => 'sn', 'translation_key' => 'countries.codes.sn', 'country_code_alpha3' => 'sen', 'country_code_m49_numeric' => '686'],
            ['id' => 'rs', 'original_name' => 'Serbia', 'country_code_alpha2' => 'rs', 'translation_key' => 'countries.codes.rs', 'country_code_alpha3' => 'srb', 'country_code_m49_numeric' => '688'],
            ['id' => 'sc', 'original_name' => 'Seychelles', 'country_code_alpha2' => 'sc', 'translation_key' => 'countries.codes.sc', 'country_code_alpha3' => 'syc', 'country_code_m49_numeric' => '690'],
            ['id' => 'sl', 'original_name' => 'Sierra Leone', 'country_code_alpha2' => 'sl', 'translation_key' => 'countries.codes.sl', 'country_code_alpha3' => 'sle', 'country_code_m49_numeric' => '694'],
            ['id' => 'sg', 'original_name' => 'Singapore', 'country_code_alpha2' => 'sg', 'translation_key' => 'countries.codes.sg', 'country_code_alpha3' => 'sgp', 'country_code_m49_numeric' => '702'],
            ['id' => 'sx', 'original_name' => 'Sint Maarten (Dutch part)', 'country_code_alpha2' => 'sx', 'translation_key' => 'countries.codes.sx', 'country_code_alpha3' => 'sxm', 'country_code_m49_numeric' => '534', 'alias' => 'sint maarten'],
            ['id' => 'sk', 'original_name' => 'Slovakia', 'country_code_alpha2' => 'sk', 'translation_key' => 'countries.codes.sk', 'country_code_alpha3' => 'svk', 'country_code_m49_numeric' => '703'],
            ['id' => 'si', 'original_name' => 'Slovenia', 'country_code_alpha2' => 'si', 'translation_key' => 'countries.codes.si', 'country_code_alpha3' => 'svn', 'country_code_m49_numeric' => '705'],
            ['id' => 'sb', 'original_name' => 'Solomon Islands', 'country_code_alpha2' => 'sb', 'translation_key' => 'countries.codes.sb', 'country_code_alpha3' => 'slb', 'country_code_m49_numeric' => '90'],
            ['id' => 'so', 'original_name' => 'Somalia', 'country_code_alpha2' => 'so', 'translation_key' => 'countries.codes.so', 'country_code_alpha3' => 'som', 'country_code_m49_numeric' => '706'],
            ['id' => 'za', 'original_name' => 'South Africa', 'country_code_alpha2' => 'za', 'translation_key' => 'countries.codes.za', 'country_code_alpha3' => 'zaf', 'country_code_m49_numeric' => '710'],
            ['id' => 'gs', 'original_name' => 'South Georgia and the South Sandwich Islands', 'country_code_alpha2' => 'gs', 'translation_key' => 'countries.codes.gs', 'country_code_alpha3' => 'sgs', 'country_code_m49_numeric' => '239'],
            ['id' => 'ss', 'original_name' => 'South Sudan', 'country_code_alpha2' => 'ss', 'translation_key' => 'countries.codes.ss', 'country_code_alpha3' => 'ssd', 'country_code_m49_numeric' => '728'],
            ['id' => 'es', 'original_name' => 'Spain', 'country_code_alpha2' => 'es', 'translation_key' => 'countries.codes.es', 'country_code_alpha3' => 'esp', 'country_code_m49_numeric' => '724'],
            ['id' => 'lk', 'original_name' => 'Sri Lanka', 'country_code_alpha2' => 'lk', 'translation_key' => 'countries.codes.lk', 'country_code_alpha3' => 'lka', 'country_code_m49_numeric' => '144'],
            ['id' => 'sd', 'original_name' => 'Sudan', 'country_code_alpha2' => 'sd', 'translation_key' => 'countries.codes.sd', 'country_code_alpha3' => 'sdn', 'country_code_m49_numeric' => '729'],
            ['id' => 'sr', 'original_name' => 'Suriname', 'country_code_alpha2' => 'sr', 'translation_key' => 'countries.codes.sr', 'country_code_alpha3' => 'sur', 'country_code_m49_numeric' => '740'],
            ['id' => 'sj', 'original_name' => 'Svalbard and Jan Mayen', 'country_code_alpha2' => 'sj', 'translation_key' => 'countries.codes.sj', 'country_code_alpha3' => 'sjm', 'country_code_m49_numeric' => '744'],
            ['id' => 'sz', 'original_name' => 'Swaziland', 'country_code_alpha2' => 'sz', 'translation_key' => 'countries.codes.sz', 'country_code_alpha3' => 'swz', 'country_code_m49_numeric' => '748'],
            ['id' => 'se', 'original_name' => 'Sweden', 'country_code_alpha2' => 'se', 'translation_key' => 'countries.codes.se', 'country_code_alpha3' => 'swe', 'country_code_m49_numeric' => '752'],
            ['id' => 'ch', 'original_name' => 'Switzerland', 'country_code_alpha2' => 'ch', 'translation_key' => 'countries.codes.ch', 'country_code_alpha3' => 'che', 'country_code_m49_numeric' => '756'],
            ['id' => 'sy', 'original_name' => 'Syrian Arab Republic', 'country_code_alpha2' => 'sy', 'translation_key' => 'countries.codes.sy', 'country_code_alpha3' => 'syr', 'country_code_m49_numeric' => '760', 'alias' => 'syria'],
            ['id' => 'tw', 'original_name' => 'Taiwan, Province of China', 'country_code_alpha2' => 'tw', 'translation_key' => 'countries.codes.tw', 'country_code_alpha3' => 'twn', 'country_code_m49_numeric' => '158', 'alias' => 'taiwan'],
            ['id' => 'tj', 'original_name' => 'Tajikistan', 'country_code_alpha2' => 'tj', 'translation_key' => 'countries.codes.tj', 'country_code_alpha3' => 'tjk', 'country_code_m49_numeric' => '762'],
            ['id' => 'tz', 'original_name' => 'Tanzania, United Republic of', 'country_code_alpha2' => 'tz', 'translation_key' => 'countries.codes.tz', 'country_code_alpha3' => 'tza', 'country_code_m49_numeric' => '834', 'alias' => 'tanzania'],
            ['id' => 'th', 'original_name' => 'Thailand', 'country_code_alpha2' => 'th', 'translation_key' => 'countries.codes.th', 'country_code_alpha3' => 'tha', 'country_code_m49_numeric' => '764'],
            ['id' => 'tl', 'original_name' => 'Timor-Leste', 'country_code_alpha2' => 'tl', 'translation_key' => 'countries.codes.tl', 'country_code_alpha3' => 'tls', 'country_code_m49_numeric' => '626'],
            ['id' => 'tg', 'original_name' => 'Togo', 'country_code_alpha2' => 'tg', 'translation_key' => 'countries.codes.tg', 'country_code_alpha3' => 'tgo', 'country_code_m49_numeric' => '768'],
            ['id' => 'tk', 'original_name' => 'Tokelau', 'country_code_alpha2' => 'tk', 'translation_key' => 'countries.codes.tk', 'country_code_alpha3' => 'tkl', 'country_code_m49_numeric' => '772'],
            ['id' => 'to', 'original_name' => 'Tonga', 'country_code_alpha2' => 'to', 'translation_key' => 'countries.codes.to', 'country_code_alpha3' => 'ton', 'country_code_m49_numeric' => '776'],
            ['id' => 'tt', 'original_name' => 'Trinidad and Tobago', 'country_code_alpha2' => 'tt', 'translation_key' => 'countries.codes.tt', 'country_code_alpha3' => 'tto', 'country_code_m49_numeric' => '780'],
            ['id' => 'tn', 'original_name' => 'Tunisia', 'country_code_alpha2' => 'tn', 'translation_key' => 'countries.codes.tn', 'country_code_alpha3' => 'tun', 'country_code_m49_numeric' => '788'],
            ['id' => 'tr', 'original_name' => 'Turkey', 'country_code_alpha2' => 'tr', 'translation_key' => 'countries.codes.tr', 'country_code_alpha3' => 'tur', 'country_code_m49_numeric' => '792'],
            ['id' => 'tm', 'original_name' => 'Turkmenistan', 'country_code_alpha2' => 'tm', 'translation_key' => 'countries.codes.tm', 'country_code_alpha3' => 'tkm', 'country_code_m49_numeric' => '795'],
            ['id' => 'tc', 'original_name' => 'Turks and Caicos Islands', 'country_code_alpha2' => 'tc', 'translation_key' => 'countries.codes.tc', 'country_code_alpha3' => 'tca', 'country_code_m49_numeric' => '796'],
            ['id' => 'tv', 'original_name' => 'Tuvalu', 'country_code_alpha2' => 'tv', 'translation_key' => 'countries.codes.tv', 'country_code_alpha3' => 'tuv', 'country_code_m49_numeric' => '798'],
            ['id' => 'ug', 'original_name' => 'Uganda', 'country_code_alpha2' => 'ug', 'translation_key' => 'countries.codes.ug', 'country_code_alpha3' => 'uga', 'country_code_m49_numeric' => '800'],
            ['id' => 'ua', 'original_name' => 'Ukraine', 'country_code_alpha2' => 'ua', 'translation_key' => 'countries.codes.ua', 'country_code_alpha3' => 'ukr', 'country_code_m49_numeric' => '804'],
            ['id' => 'ae', 'original_name' => 'United Arab Emirates', 'country_code_alpha2' => 'ae', 'translation_key' => 'countries.codes.ae', 'country_code_alpha3' => 'are', 'country_code_m49_numeric' => '784'],
            ['id' => 'gb', 'original_name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_code_alpha2' => 'gb', 'translation_key' => 'countries.codes.gb', 'country_code_alpha3' => 'gbr', 'country_code_m49_numeric' => '826', 'alias' => 'uk'],
            ['id' => 'us', 'original_name' => 'United States of America', 'country_code_alpha2' => 'us', 'translation_key' => 'countries.codes.us', 'country_code_alpha3' => 'usa', 'country_code_m49_numeric' => '840', 'alias' => 'usa'],
            ['id' => 'um', 'original_name' => 'United States Minor Outlying Islands', 'country_code_alpha2' => 'um', 'translation_key' => 'countries.codes.um', 'country_code_alpha3' => 'umi', 'country_code_m49_numeric' => '581'],
            ['id' => 'uy', 'original_name' => 'Uruguay', 'country_code_alpha2' => 'uy', 'translation_key' => 'countries.codes.uy', 'country_code_alpha3' => 'ury', 'country_code_m49_numeric' => '858'],
            ['id' => 'uz', 'original_name' => 'Uzbekistan', 'country_code_alpha2' => 'uz', 'translation_key' => 'countries.codes.uz', 'country_code_alpha3' => 'uzb', 'country_code_m49_numeric' => '860'],
            ['id' => 'vu', 'original_name' => 'Vanuatu', 'country_code_alpha2' => 'vu', 'translation_key' => 'countries.codes.vu', 'country_code_alpha3' => 'vut', 'country_code_m49_numeric' => '548'],
            ['id' => 've', 'original_name' => 'Venezuela (Bolivarian Republic of)', 'country_code_alpha2' => 've', 'translation_key' => 'countries.codes.ve', 'country_code_alpha3' => 'ven', 'country_code_m49_numeric' => '862', 'alias' => 'venezuela'],
            ['id' => 'vn', 'original_name' => 'Viet Nam', 'country_code_alpha2' => 'vn', 'translation_key' => 'countries.codes.vn', 'country_code_alpha3' => 'vnm', 'country_code_m49_numeric' => '704', 'alias' => 'vietnam'],
            ['id' => 'vg', 'original_name' => 'Virgin Islands (British)', 'country_code_alpha2' => 'vg', 'translation_key' => 'countries.codes.vg', 'country_code_alpha3' => 'vgb', 'country_code_m49_numeric' => '92', 'alias' => 'british virgin islands'],
            ['id' => 'vi', 'original_name' => 'Virgin Islands (U.S.)', 'country_code_alpha2' => 'vi', 'translation_key' => 'countries.codes.vi', 'country_code_alpha3' => 'vir', 'country_code_m49_numeric' => '850', 'alias' => 'u.s. virgin islands'],
            ['id' => 'wf', 'original_name' => 'Wallis and Futuna', 'country_code_alpha2' => 'wf', 'translation_key' => 'countries.codes.wf', 'country_code_alpha3' => 'wlf', 'country_code_m49_numeric' => '876'],
            ['id' => 'eh', 'original_name' => 'Western Sahara', 'country_code_alpha2' => 'eh', 'translation_key' => 'countries.codes.eh', 'country_code_alpha3' => 'esh', 'country_code_m49_numeric' => '732'],
            ['id' => 'ye', 'original_name' => 'Yemen', 'country_code_alpha2' => 'ye', 'translation_key' => 'countries.codes.ye', 'country_code_alpha3' => 'yem', 'country_code_m49_numeric' => '887'],
            ['id' => 'zm', 'original_name' => 'Zambia', 'country_code_alpha2' => 'zm', 'translation_key' => 'countries.codes.zm', 'country_code_alpha3' => 'zmb', 'country_code_m49_numeric' => '894'],
            ['id' => 'zw', 'original_name' => 'Zimbabwe', 'country_code_alpha2' => 'zw', 'translation_key' => 'countries.codes.zw', 'country_code_alpha3' => 'zwe', 'country_code_m49_numeric' => '716'],
        ];

        DB::beginTransaction();
        try {
            foreach ($list as $item) {
                $record = FF_contries::find($item['id']);
                if (!$record) {
                    FF_contries::create([
                        'id' => $item['id'],
                        'original_name' => $item['original_name']
                    ]);
                }
            }

        } catch (Exception $e) {
            DB::rollback();
            echo 'Point of failure '. $e->getCode() . ' ' . $e->getMessage();
            throw new Exception($e);
        }
        DB::commit();
    }
}
